(()=>{
'use strict';
const S=window.TASK5_SUMMARY, RAW=window.TASK5_RAW||[], CLEAN=window.TASK5_CLEAN||[], LOG=window.TASK5_LOG||[];
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
let currentView='overview', filteredRaw=[...RAW], filteredClean=[...CLEAN], filteredLog=[...LOG], sortState={key:'application_id',dir:1}, page=1;
const idDate=new Map(RAW.map(r=>[r.application_id,(r.submitted_at||'').slice(0,10)]));
const idRaw=new Map(RAW.map(r=>[r.application_id,r]));
const fmt=n=>Number(n||0).toLocaleString();
const escapeHTML=x=>String(x??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const toast=msg=>{const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)};
const uniq=(arr,key)=>[...new Set(arr.map(x=>x[key]).filter(Boolean))].sort();
function optionize(id,vals,first){const e=$(id);e.innerHTML=`<option>${first}</option>`+vals.map(v=>`<option>${escapeHTML(v)}</option>`).join('')}
optionize('#departmentFilter',uniq(CLEAN,'preferred_department'),'All Departments'); optionize('#cityFilter',uniq(CLEAN,'city'),'All Cities'); optionize('#educationFilter',uniq(CLEAN,'education_level'),'All Levels');

function safeStorageGet(k){try{return localStorage.getItem(k)}catch(e){return null}} function safeStorageSet(k,v){try{localStorage.setItem(k,v)}catch(e){}}
const saved=safeStorageGet('task5-theme'); document.documentElement.dataset.theme=saved||'dark'; updateThemeIcon();
function updateThemeIcon(){const light=document.documentElement.dataset.theme==='light'; $('#themeIcon').textContent=light?'☀':'☾'; $('#themeBtn').title=light?'Switch to night view':'Switch to day view'}
$('#themeBtn').addEventListener('click',()=>{document.documentElement.dataset.theme=document.documentElement.dataset.theme==='dark'?'light':'dark';safeStorageSet('task5-theme',document.documentElement.dataset.theme);updateThemeIcon();renderCurrent();});
$('#menuBtn').addEventListener('click',()=>$('#sidebar').classList.toggle('open'));
$$('.nav-item').forEach(b=>b.onclick=()=>{currentView=b.dataset.view;$$('.nav-item').forEach(x=>x.classList.toggle('active',x===b));$('#sidebar').classList.remove('open');page=1;renderCurrent()});
$('#applyFilters').onclick=()=>{applyFilters();toast('Filters applied')}; $('#resetFilters').onclick=resetFilters;
$('#globalSearch').addEventListener('input',()=>{applyFilters(false)}); $('#skillFilter').addEventListener('keydown',e=>{if(e.key==='Enter')applyFilters()});
document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();$('#globalSearch').focus()}});
$('#modalClose').onclick=()=>$('#modalBackdrop').classList.remove('show'); $('#modalBackdrop').onclick=e=>{if(e.target.id==='modalBackdrop')e.currentTarget.classList.remove('show')};

function applyFilters(show=true){
 const d1=$('#dateFrom').value,d2=$('#dateTo').value,dept=$('#departmentFilter').value,city=$('#cityFilter').value,edu=$('#educationFilter').value,skill=$('#skillFilter').value.trim().toLowerCase(),q=$('#globalSearch').value.trim().toLowerCase();
 const predRaw=r=>{let date=(r.submitted_at||'').slice(0,10); if(d1&&date<d1||d2&&date>d2)return false;if(dept!=='All Departments'&&r.department_clean!==dept)return false;if(city!=='All Cities'&&r.city_clean!==city)return false;if(edu!=='All Levels'&&r.education_clean!==edu)return false;if(skill&&!String(r.skills_clean||'').toLowerCase().includes(skill))return false;if(q&&!Object.values(r).some(v=>String(v).toLowerCase().includes(q)))return false;return true};
 const predClean=r=>{let date=(r.submitted_at||'').slice(0,10); if(d1&&date<d1||d2&&date>d2)return false;if(dept!=='All Departments'&&r.preferred_department!==dept)return false;if(city!=='All Cities'&&r.city!==city)return false;if(edu!=='All Levels'&&r.education_level!==edu)return false;if(skill&&!String(r.skills||'').toLowerCase().includes(skill))return false;if(q&&!Object.values(r).some(v=>String(v).toLowerCase().includes(q)))return false;return true};
 filteredRaw=RAW.filter(predRaw);filteredClean=CLEAN.filter(predClean);const ids=new Set(filteredRaw.map(r=>r.application_id));filteredLog=LOG.filter(x=>ids.has(x.application_id));page=1;renderCurrent(); if(show&&filteredRaw.length===0)toast('No records match the selected filters');
}
function resetFilters(){ $('#dateFrom').value='2025-03-01';$('#dateTo').value='2025-04-29';$('#departmentFilter').selectedIndex=0;$('#cityFilter').selectedIndex=0;$('#educationFilter').selectedIndex=0;$('#skillFilter').value='';$('#globalSearch').value=''; filteredRaw=[...RAW];filteredClean=[...CLEAN];filteredLog=[...LOG];page=1;renderCurrent();toast('Filters reset') }
function issueCount(type){return filteredLog.filter(x=>x.issue_type===type).length}
function qualityScore(){if(!filteredRaw.length)return 0;const miss=issueCount('Missing value'),dup=issueCount('Duplicate record'),out=issueCount('Outlier/invalid numeric'),std=filteredLog.filter(x=>!['Missing value','Duplicate record','Outlier/invalid numeric'].includes(x.issue_type)).length;const denom=Math.max(filteredRaw.length,1);let penalty=(miss/(denom*10))*35+(dup/denom)*25+(out/(denom*4))*20+(std/(denom*8))*20;return Math.max(0,Math.min(100,100-penalty));}
function kpi(icon,label,value,sub,accent,trend='resolved'){return `<div class="kpi" style="--accent:${accent}"><div class="kpi-icon">${icon}</div><div><div class="value">${value}</div><b>${label}</b><small>${sub}</small></div><span class="trend">✓ ${trend}</span></div>`}
function panel(title,sub,body,extra=''){return `<article class="panel"><div class="panel-head"><div><h3>${title}</h3>${sub?`<div class="panel-sub">${sub}</div>`:''}</div>${extra}</div>${body}</article>`}
function filteredMetrics(){return {raw:filteredRaw.length,clean:filteredClean.length,missing:issueCount('Missing value'),dup:issueCount('Duplicate record'),out:issueCount('Outlier/invalid numeric'),std:filteredLog.filter(x=>!['Missing value','Duplicate record','Outlier/invalid numeric'].includes(x.issue_type)).length,q:qualityScore()}}

function pipelineHTML(m){const steps=[['▱','Raw Data',m.raw+' records'],['◉','Fix Missing',m.missing+' fixes'],['▧','Remove Duplicates',m.dup+' removed'],['✕','Treat Outliers',m.out+' treated'],['⚙','Standardize',m.std+' fixes'],['✓','Validate','rules passed'],['▤','Clean Data',m.clean+' records']];return `<div class="pipeline">${steps.map(x=>`<div class="step"><div class="bubble">${x[0]}</div><b>${x[1]}</b><small>${x[2]}</small></div>`).join('')}</div>`}
function sankeySVG(m){const w=520,h=170, left=55,right=450;const issues=[['Missing',m.missing,'#17d9ff'],['Duplicates',m.dup,'#6586ff'],['Outliers',m.out,'#26e6b3'],['Standardize',m.std,'#39c2ff']];let total=Math.max(issues.reduce((a,b)=>a+b[1],0),1),y=15;const maxIssue=Math.max(...issues.map(x=>x[1]),1);let paths='',nodes='';issues.forEach((x,i)=>{let hh=Math.max(11,55*x[1]/maxIssue);let yy=18+i*34;let sw=Math.max(2,18*x[1]/total);paths+=`<path d="M 88 ${85+i*2} C 180 ${85+i*2}, 220 ${yy+hh/2}, 318 ${yy+hh/2}" stroke="${x[2]}" stroke-opacity=".35" stroke-width="${sw+5}" fill="none"/>`+`<path d="M 338 ${yy+hh/2} C 385 ${yy+hh/2}, 405 ${85}, 445 85" stroke="${x[2]}" stroke-opacity=".38" stroke-width="${sw+5}" fill="none"/>`;nodes+=`<rect x="318" y="${yy}" width="20" height="${hh}" rx="3" fill="${x[2]}"/><text x="344" y="${yy+hh/2+3}" class="sankey-label">${x[0]} ${fmt(x[1])}</text>`});return `<svg class="svg-wrap" viewBox="0 0 ${w} ${h}" preserveAspectRatio="none"><rect x="50" y="50" width="38" height="70" rx="5" fill="#526f91"/><text x="15" y="145" class="sankey-label">Raw ${fmt(m.raw)}</text>${paths}${nodes}<rect x="445" y="45" width="45" height="80" rx="5" fill="#26e6b3"/><text x="428" y="145" class="sankey-label">Clean ${fmt(m.clean)}</text></svg>`}
function calendarHTML(){const map=new Map();filteredLog.forEach(x=>{const d=idDate.get(x.application_id);if(d)map.set(d,(map.get(d)||0)+1)});let dates=[];for(let d=new Date('2025-03-01T00:00:00');d<=new Date('2025-04-29T00:00:00');d.setDate(d.getDate()+1))dates.push(new Date(d));const max=Math.max(...[...map.values(),1]);let cells='';['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].forEach((dow,ri)=>{cells+=`<span class="dow" style="grid-column:1;grid-row:${ri+1}">${dow.slice(0,1)}</span>`});dates.forEach((d,i)=>{let week=Math.floor((i+5)/7)+2,row=d.getDay()+1,key=d.toISOString().slice(0,10),v=map.get(key)||0,alpha=.14+.82*(v/max);cells+=`<div class="daycell" style="grid-column:${week};grid-row:${row};background:rgba(38,230,179,${alpha.toFixed(2)})" data-tip="${key}: ${v} issues"></div>`});return `<div class="calendar">${cells}</div>`}
function stats(arr,key){let a=arr.map(x=>Number(x[key])).filter(Number.isFinite).sort((a,b)=>a-b);if(!a.length)return {min:0,q1:0,med:0,q3:0,max:0,outs:[]};const q=p=>a[Math.floor((a.length-1)*p)];let q1=q(.25),med=q(.5),q3=q(.75),iqr=q3-q1,lo=q1-1.5*iqr,hi=q3+1.5*iqr,outs=a.filter(v=>v<lo||v>hi);return {min:Math.max(a[0],lo),q1,med,q3,max:Math.min(a[a.length-1],hi),outs}}
function boxplotSVG(){const fields=[['age','Age'],['cgpa','CGPA'],['experience_months','Experience']];let w=420,h=170;let parts=`<svg class="svg-wrap" viewBox="0 0 ${w} ${h}">`;fields.forEach((f,i)=>{let st=stats(filteredRaw,f[0]);let vals=filteredRaw.map(x=>Number(x[f[0]])).filter(Number.isFinite), mx=Math.max(...vals,1), y=v=>135-(v/mx)*105, x=85+i*125;parts+=`<line x1="${x}" y1="${y(st.min)}" x2="${x}" y2="${y(st.max)}" stroke="#6ca5be"/><line x1="${x-14}" y1="${y(st.min)}" x2="${x+14}" y2="${y(st.min)}" stroke="#6ca5be"/><line x1="${x-14}" y1="${y(st.max)}" x2="${x+14}" y2="${y(st.max)}" stroke="#6ca5be"/><rect x="${x-24}" y="${y(st.q3)}" width="48" height="${Math.max(5,y(st.q1)-y(st.q3))}" fill="#0b7099" stroke="#17d9ff"/><line x1="${x-24}" y1="${y(st.med)}" x2="${x+24}" y2="${y(st.med)}" stroke="#26e6b3" stroke-width="2"/>`;st.outs.slice(0,12).forEach(v=>parts+=`<circle cx="${x+(Math.random()*10-5)}" cy="${y(v)}" r="2.5" fill="#ff5f6d"/>`);parts+=`<text x="${x}" y="158" text-anchor="middle" class="chart-label">${f[1]}</text>`});return parts+'</svg>'}
function treemapHTML(){const c={missing:issueCount('Missing value'),dup:issueCount('Duplicate record'),out:issueCount('Outlier/invalid numeric'),std:filteredLog.filter(x=>!['Missing value','Duplicate record','Outlier/invalid numeric'].includes(x.issue_type)).length};const total=Math.max(c.missing+c.dup+c.out+c.std,1);return `<div class="treemap"><div class="tree a"><b>${fmt(c.std)}</b><span>Standardization</span><small>${(c.std/total*100).toFixed(1)}%</small></div><div class="tree b"><b>${fmt(c.missing)}</b><span>Missing</span><small>${(c.missing/total*100).toFixed(1)}%</small></div><div class="tree c"><b>${fmt(c.dup)}</b><span>Duplicates</span><small>${(c.dup/total*100).toFixed(1)}%</small></div><div class="tree d"><b>${fmt(c.out)}</b><span>Outliers</span><small>${(c.out/total*100).toFixed(1)}%</small></div><div class="tree e"><b>${fmt(total)}</b><span>Total fixes</span></div></div>`}
function qualityHeatHTML(){const fields=['applicant_name','email','phone','city','education_level','cgpa','skills','experience_months','preferred_department'];const n=Math.max(filteredRaw.length,1);return `<div class="quality-heat"><b>Column</b><b>Before</b><b>After</b><b>Δ</b>${fields.map(f=>{let issues=filteredLog.filter(x=>x.field===f).length, before=Math.max(0,100-issues/n*100),after=100,bc=`hsl(${Math.round(before*1.2)},72%,45%)`,ac='#26e6b3';return `<span>${f.replaceAll('_',' ')}</span><div class="qcell"><div class="qbar" style="width:${before}%;background:${bc}"></div></div><div class="qcell"><div class="qbar" style="width:${after}%;background:${ac}"></div></div><b style="color:var(--teal)">+${(after-before).toFixed(0)}</b>`}).join('')}</div>`}
function progressHTML(m){let vals=[['Missing Values Fixed',m.missing,S.missing_values_fixed],['Duplicates Removed',m.dup,S.duplicates_removed],['Outliers Treated',m.out,S.outliers_treated],['Quality Score',m.q,100]];return `<div class="progress-list">${vals.map((x,i)=>{let p=i===3?x[1]:Math.min(100,(x[1]/Math.max(x[2],1))*100);return `<div class="progress-row"><span>${x[0]}</span><b>${p.toFixed(0)}%</b><div class="track"><div class="fill" style="width:${p}%"></div></div></div>`}).join('')}</div>`}
function correctionsTable(){let rows=filteredLog.filter(x=>x.field!=='record').slice(0,8);if(!rows.length)return `<div class="empty">No cleaning actions match the current filters.</div>`;return `<div class="table-wrap"><table><thead><tr><th>ID</th><th>Field</th><th>Issue</th><th>Original</th><th>Corrected</th><th>Status</th></tr></thead><tbody>${rows.map(x=>`<tr><td>${x.application_id}</td><td>${x.field}</td><td class="tag-red">${x.issue_type}</td><td title="${escapeHTML(x.original_value)}">${escapeHTML(x.original_value)}</td><td title="${escapeHTML(x.cleaned_value)}">${escapeHTML(x.cleaned_value)}</td><td><span class="status">✓ Fixed</span></td></tr>`).join('')}</tbody></table></div>`}
function checklistHTML(){return `<div class="checklist"><div class="checkitem"><span class="check">✓</span>Profile dataset structure</div><div class="checkitem"><span class="check">✓</span>Handle missing values</div><div class="checkitem"><span class="check">✓</span>Remove duplicate records</div><div class="checkitem"><span class="check">✓</span>Detect and treat outliers</div><div class="checkitem"><span class="check">✓</span>Standardize formats and text</div><div class="checkitem"><span class="check">✓</span>Validate against quality rules</div><div class="checkitem"><span class="check">✓</span>Generate clean dataset</div><div class="checkitem"><span class="check">✓</span>Review and export report</div></div>`}
function overview(){const m=filteredMetrics();return `<div class="kpi-grid">${kpi('▤','Raw Records',fmt(m.raw),'Filtered application records','#3c78ff')}${kpi('✓','Clean Records',fmt(m.clean),'Analysis-ready records','#26e6b3')}${kpi('⌕','Missing Values Fixed',fmt(m.missing),'Imputed / explicitly categorized','#17d9ff')}${kpi('⬡','Duplicates Removed',fmt(m.dup),'Normalized identity matching','#a855f7')}${kpi('⌁','Outliers Treated',fmt(m.out),'Invalid numeric values corrected','#ff5f6d')}${kpi('◈','Data Quality Score',m.q.toFixed(1)+'%','Rule-based filtered score','#26e6b3')}</div>
<div class="grid2">${panel('Data Cleaning Pipeline','Transforming raw internship application data into a clean, reliable dataset.',pipelineHTML(m),'<div class="badges"><span class="badge good">Automated</span><span class="badge">Reproducible</span><span class="badge">Audit Ready</span></div>')}${panel('Data Flow Through Cleaning Process','Hover over dashboard elements to inspect details.',sankeySVG(m))}</div>
<div class="grid3">${panel('Issue Density by Application Date','Calendar heatmap of cleaning actions.',calendarHTML())}${panel('Outlier Detection Across Key Fields','Box plots highlight abnormal numeric values.',boxplotSVG())}${panel('Issue Categories','Proportion of detected data-quality issues.',treemapHTML())}</div>
<div class="grid4">${panel('Data Quality Before vs After','Issue rate by field; darker cells indicate weaker quality.',qualityHeatHTML())}${panel('KPI Progress','Cleaning progress within the current filter scope.',progressHTML(m))}${panel('Recent Record Corrections','Before/after examples from the cleaning audit log.',correctionsTable(),'<button class="small-btn" data-action="view-log">View All</button>')}${panel('Cleaning Checklist','All Task 5 requirements mapped to verified steps.',checklistHTML(),'<span class="badge good">8/8 complete</span>')}</div>
<div class="section-title"><div></div><div class="toolbar"><button data-action="download">⇩ Download Cleaned CSV</button><button data-action="print">▧ Export Report</button></div></div>`}

function sectionHeader(title,sub){return `<div class="section-title"><div><h2>${title}</h2><p>${sub}</p></div><div class="toolbar"><button data-action="download">⇩ Download Cleaned CSV</button><button data-action="print">▧ Export Report</button></div></div>`}
function profiling(){let m=filteredMetrics(),fields=['applicant_name','email','phone','age','gender','city','province','education_level','university','cgpa','skills','experience_months','preferred_department','application_source','expected_stipend_pkr'];let cards=[['Rows',m.raw],['Columns',18],['Cleaning Actions',filteredLog.length],['Clean Rows',m.clean]];return sectionHeader('Data Profiling','Inspect structure, completeness, cardinality, and field quality before cleaning.')+`<div class="metric-grid">${cards.map(x=>`<div class="metric-card"><small>${x[0]}</small><b>${fmt(x[1])}</b></div>`).join('')}</div><div class="grid2">${panel('Column Profile','Missingness, unique values, and issue counts.',`<div class="table-wrap"><table><thead><tr><th>Column</th><th>Missing</th><th>Unique</th><th>Logged Issues</th><th>Quality</th></tr></thead><tbody>${fields.map(f=>{let miss=filteredRaw.filter(r=>r[f]==null||r[f]==='').length,unq=new Set(filteredRaw.map(r=>String(r[f]))).size,iss=filteredLog.filter(x=>x.field===f).length,q=100-Math.min(100,iss/Math.max(filteredRaw.length,1)*100);return `<tr><td>${f}</td><td>${miss}</td><td>${unq}</td><td>${iss}</td><td><span class="status">${q.toFixed(1)}%</span></td></tr>`}).join('')}</tbody></table></div>`)}${panel('Quality Heatmap','Before vs after cleaning by key field.',qualityHeatHTML())}</div>`}
function missing(){let fields=['phone','city','university','cgpa','skills','linkedin_url','gender'];let vals=fields.map(f=>[f,filteredLog.filter(x=>x.field===f&&x.issue_type==='Missing value').length]);let max=Math.max(...vals.map(x=>x[1]),1);return sectionHeader('Missing Values','Identify nulls and apply transparent, field-appropriate handling rules.')+`<div class="grid2">${panel('Missing Values by Field','Counts update with dashboard filters.',`<div class="progress-list">${vals.map(x=>`<div class="progress-row"><span>${x[0]}</span><b>${x[1]}</b><div class="track"><div class="fill" style="width:${x[1]/max*100}%"></div></div></div>`).join('')}</div>`)}${panel('Handling Strategy','Rules are designed to preserve meaning rather than invent information.',`<div class="checklist"><div class="checkitem"><span class="check">✓</span>CGPA → valid median imputation</div><div class="checkitem"><span class="check">✓</span>City → province-level mode</div><div class="checkitem"><span class="check">✓</span>Gender → “Prefer not to say”</div><div class="checkitem"><span class="check">✓</span>University / Skills / LinkedIn / Phone → explicit “Not Provided/Specified” category</div></div>`)}</div>${panel('Missing Value Corrections','Audit trail of values handled by Pandas.',logTable('Missing value'))}`}
function logTable(type){let rows=filteredLog.filter(x=>!type||x.issue_type===type);return `<div class="table-wrap"><table><thead><tr><th>Application ID</th><th>Field</th><th>Original</th><th>Cleaned</th><th>Issue</th><th>Action</th></tr></thead><tbody>${rows.slice(0,120).map(x=>`<tr><td>${x.application_id}</td><td>${x.field}</td><td>${escapeHTML(x.original_value)}</td><td>${escapeHTML(x.cleaned_value)}</td><td>${x.issue_type}</td><td>${x.action}</td></tr>`).join('')}</tbody></table></div>`}
function duplicates(){let rows=filteredLog.filter(x=>x.issue_type==='Duplicate record');let detail=rows.map(x=>idRaw.get(x.application_id)).filter(Boolean);return sectionHeader('Duplicate Detection','Normalize identifiers first, then remove repeated applicant identities.')+`<div class="metric-grid"><div class="metric-card"><small>Duplicates removed</small><b>${rows.length}</b></div><div class="metric-card"><small>Rule</small><b style="font-size:13px">Email + Phone</b></div><div class="metric-card"><small>Fallback</small><b style="font-size:13px">Name + Email</b></div><div class="metric-card"><small>Keep strategy</small><b style="font-size:13px">First valid record</b></div></div>${panel('Removed Duplicate Applications','Duplicate matching is performed after email, phone and name normalization.',`<div class="table-wrap"><table><thead><tr><th>ID</th><th>Name</th><th>Email</th><th>Phone</th><th>Department</th><th>Submitted</th><th>Status</th></tr></thead><tbody>${detail.slice(0,100).map(r=>`<tr><td>${r.application_id}</td><td>${escapeHTML(r.applicant_name)}</td><td>${escapeHTML(r.email)}</td><td>${escapeHTML(r.phone)}</td><td>${r.department_clean}</td><td>${r.submitted_at}</td><td><span class="tag-red">Removed</span></td></tr>`).join('')}</tbody></table></div>`)}`}
function outliers(){let rows=filteredLog.filter(x=>x.issue_type==='Outlier/invalid numeric');return sectionHeader('Outlier Treatment','Detect impossible or extreme values in age, CGPA, experience and stipend.')+`<div class="grid2">${panel('Outlier Detection Across Key Fields','Raw-value box plots; red points are outside the IQR/valid range.',boxplotSVG())}${panel('Treatment Rules','Clearly defined, reproducible validity checks.',`<div class="checklist"><div class="checkitem"><span class="check">✓</span>Age valid range: 18–45</div><div class="checkitem"><span class="check">✓</span>CGPA valid range: 0–4</div><div class="checkitem"><span class="check">✓</span>Experience valid range: 0–60 months</div><div class="checkitem"><span class="check">✓</span>Expected stipend valid range: PKR 5,000–100,000</div><div class="checkitem"><span class="check">✓</span>Invalid values replaced with a valid median</div></div>`)}</div>${panel('Outlier Correction Log',`${rows.length} outlier/invalid numeric actions in the current selection.`,logTable('Outlier/invalid numeric'))}`}
function standardization(){let rows=filteredLog.filter(x=>!['Missing value','Duplicate record','Outlier/invalid numeric'].includes(x.issue_type));return sectionHeader('Standardization & Structuring','Convert inconsistent text, categories, phone numbers, skills and URLs into analysis-ready formats.')+`<div class="grid2">${panel('Transformation Coverage','Standardization fixes by field.',qualityHeatHTML())}${panel('Canonical Rules','Consistent values improve grouping, filtering and downstream analysis.',`<div class="checklist"><div class="checkitem"><span class="check">✓</span>Names → trimmed Title Case</div><div class="checkitem"><span class="check">✓</span>Emails → lowercase and whitespace removed</div><div class="checkitem"><span class="check">✓</span>Phones → 11-digit Pakistan format</div><div class="checkitem"><span class="check">✓</span>Cities / departments / education → canonical mappings</div><div class="checkitem"><span class="check">✓</span>Skills → canonical labels and comma delimiters</div><div class="checkitem"><span class="check">✓</span>LinkedIn URLs → normalized HTTPS form</div></div>`)}</div>${panel('Standardization Audit Log',`${rows.length} standardization actions in the current selection.`,logTable())}`}
function rules(){let rules=[['Required fields populated',filteredClean.every(r=>['applicant_name','email','phone','city','education_level','cgpa','skills'].every(k=>r[k]!=null&&String(r[k]).trim()!==''))],['No duplicate email + phone',new Set(filteredClean.map(r=>r.email+'|'+r.phone)).size===filteredClean.length],['Age within 18–45',filteredClean.every(r=>+r.age>=18&&+r.age<=45)],['CGPA within 0–4',filteredClean.every(r=>+r.cgpa>=0&&+r.cgpa<=4)],['Experience within 0–60 months',filteredClean.every(r=>+r.experience_months>=0&&+r.experience_months<=60)],['Stipend within PKR 5k–100k',filteredClean.every(r=>+r.expected_stipend_pkr>=5000&&+r.expected_stipend_pkr<=100000)],['Email normalized',filteredClean.every(r=>r.email===String(r.email).toLowerCase().trim())],['Structured submitted timestamp',filteredClean.every(r=>/^\d{4}-\d{2}-\d{2}/.test(r.submitted_at))]];return sectionHeader('Quality Rules','Automated validation confirms that the cleaned dataset is ready for efficient analysis.')+`<div class="rule-grid">${rules.map(x=>`<div class="rule-card"><strong>${x[0]}<span class="${x[1]?'rule-pass':'tag-red'}">${x[1]?'PASS':'CHECK'}</span></strong><p class="panel-sub">${x[1]?'Validation successful for the filtered cleaned records.':'Review the current filtered records.'}</p></div>`).join('')}</div>`}
function dataset(){let rows=[...filteredClean];rows.sort((a,b)=>{let x=a[sortState.key],y=b[sortState.key];if(typeof x==='number'&&typeof y==='number')return (x-y)*sortState.dir;return String(x).localeCompare(String(y))*sortState.dir});const per=25,pages=Math.max(1,Math.ceil(rows.length/per));page=Math.min(page,pages);let slice=rows.slice((page-1)*per,page*per);const cols=['application_id','applicant_name','email','phone','age','city','education_level','cgpa','skills','experience_months','preferred_department','application_source'];return sectionHeader('Clean Dataset','Search, sort, review and export the final analysis-ready internship application dataset.')+`<div class="panel"><div class="panel-head"><div><h3>${fmt(rows.length)} cleaned records</h3><div class="panel-sub">Click a column heading to sort. Click a record to inspect details.</div></div><span class="badge good">Page ${page}/${pages}</span></div><div class="table-wrap" style="max-height:520px"><table><thead><tr>${cols.map(c=>`<th data-sort="${c}" style="cursor:pointer">${c.replaceAll('_',' ')}</th>`).join('')}</tr></thead><tbody>${slice.map(r=>`<tr data-record="${r.application_id}" style="cursor:pointer">${cols.map(c=>`<td title="${escapeHTML(r[c])}">${escapeHTML(r[c])}</td>`).join('')}</tr>`).join('')}</tbody></table></div><div class="toolbar" style="justify-content:flex-end;margin-top:8px"><button data-page="prev">← Previous</button><button data-page="next">Next →</button></div></div>`}
function reports(){let m=filteredMetrics();let findings=[`Processed ${fmt(m.raw)} raw records and retained ${fmt(m.clean)} clean records in the current filter scope.`,`${fmt(m.missing)} missing values were handled using field-specific rules instead of one generic imputation method.`,`${fmt(m.dup)} duplicate records were removed after normalization of identity fields.`,`${fmt(m.out)} invalid numeric/outlier values were corrected using valid-range checks and median replacement.`,`${fmt(m.std)} format/category standardization actions improved grouping consistency.`,`The current rule-based data quality score is ${m.q.toFixed(1)}%.`];return sectionHeader('Report & Recommendations','Management-ready summary of cleaning outcomes, controls and recommended next steps.')+`<div class="grid2">${panel('Key Findings','Results update with active dashboard filters.',`<ol>${findings.map(x=>`<li style="margin:9px 0;color:var(--text)">${x}</li>`).join('')}</ol>`)}${panel('Practical Recommendations','Actions for maintaining high-quality internship application data.',`<div class="checklist"><div class="checkitem"><span class="check">1</span>Add form-level validation for phone, CGPA, age and stipend.</div><div class="checkitem"><span class="check">2</span>Use controlled dropdowns for city, degree and department.</div><div class="checkitem"><span class="check">3</span>Normalize identity fields before duplicate checks.</div><div class="checkitem"><span class="check">4</span>Run the Pandas cleaning pipeline before every reporting refresh.</div><div class="checkitem"><span class="check">5</span>Keep a cleaning log so every correction remains auditable.</div></div>`)}</div>${panel('Submission Evidence','Task 5 guideline coverage.',checklistHTML())}`}
function renderCurrent(){const map={overview,profiling,missing,duplicates,outliers,standardization,rules,dataset,reports};$('#content').innerHTML=(map[currentView]||overview)();bindDynamic()}
function bindDynamic(){$$('[data-action="download"]').forEach(b=>b.onclick=downloadCSV);$$('[data-action="print"]').forEach(b=>b.onclick=()=>window.print());$$('[data-action="view-log"]').forEach(b=>b.onclick=()=>{currentView='standardization';$$('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.view===currentView));renderCurrent()});$$('[data-sort]').forEach(h=>h.onclick=()=>{let k=h.dataset.sort;if(sortState.key===k)sortState.dir*=-1;else sortState={key:k,dir:1};renderCurrent()});$$('[data-record]').forEach(r=>r.onclick=()=>openRecord(r.dataset.record));$$('[data-page]').forEach(b=>b.onclick=()=>{if(b.dataset.page==='prev')page=Math.max(1,page-1);else page++;renderCurrent()})}
function openRecord(id){let r=CLEAN.find(x=>x.application_id===id),actions=LOG.filter(x=>x.application_id===id);if(!r)return;$('#modalContent').innerHTML=`<h2>${r.application_id} · ${escapeHTML(r.applicant_name)}</h2><p class="panel-sub">Cleaned application record and associated cleaning audit history.</p><div class="rule-grid">${Object.entries(r).slice(0,15).map(([k,v])=>`<div class="rule-card"><small>${k.replaceAll('_',' ')}</small><strong style="margin-top:5px;display:block">${escapeHTML(v)}</strong></div>`).join('')}</div><h3 style="margin-top:18px">Cleaning actions</h3>${actions.length?logTableFor(actions):'<p>No corrections were required for this record.</p>'}`;$('#modalBackdrop').classList.add('show')}
function logTableFor(rows){return `<div class="table-wrap"><table><thead><tr><th>Field</th><th>Original</th><th>Cleaned</th><th>Issue</th><th>Action</th></tr></thead><tbody>${rows.map(x=>`<tr><td>${x.field}</td><td>${escapeHTML(x.original_value)}</td><td>${escapeHTML(x.cleaned_value)}</td><td>${x.issue_type}</td><td>${x.action}</td></tr>`).join('')}</tbody></table></div>`}
function downloadCSV(){if(!filteredClean.length){toast('No cleaned records to download');return}let cols=Object.keys(filteredClean[0]);let esc=v=>'"'+String(v??'').replaceAll('"','""')+'"';let csv=[cols.join(','),...filteredClean.map(r=>cols.map(c=>esc(r[c])).join(','))].join('\r\n');let blob=new Blob([csv],{type:'text/csv;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='task5_cleaned_filtered.csv';document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(url);toast('Filtered cleaned dataset downloaded')}
renderCurrent();
})();
